# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='none'),
        ),
    ]
