# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja', '0003_auto_20180412_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='book',
        ),
        migrations.AddField(
            model_name='authors',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='ninja.books'),
        ),
    ]
