# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja', '0004_auto_20180412_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='PlaceHolder'),
        ),
    ]
