# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userd', '0003_message_msguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msgUser',
        ),
    ]
