# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userd', '0005_message_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='users',
        ),
        migrations.AddField(
            model_name='message',
            name='users',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='userd.users'),
            preserve_default=False,
        ),
    ]
