# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userd', '0006_auto_20180423_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default=111, max_length=255),
            preserve_default=False,
        ),
    ]
